// GENERATED by `supabase gen types typescript` (project vqmejpuzdyvmbwcmulmc, 2026-07-15).
// Regenerate after schema changes: supabase gen types typescript --project-id vqmejpuzdyvmbwcmulmc > src/types/database.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      courses: {
        Row: {
          code: string
          created_at: string | null
          department: string | null
          description: string | null
          id: number
          is_active: boolean | null
          name: string
          university_id: number
          updated_at: string | null
        }
        Insert: {
          code: string
          created_at?: string | null
          department?: string | null
          description?: string | null
          id?: number
          is_active?: boolean | null
          name: string
          university_id: number
          updated_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string | null
          department?: string | null
          description?: string | null
          id?: number
          is_active?: boolean | null
          name?: string
          university_id?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "courses_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      curricula: {
        Row: {
          code: string
          created_at: string | null
          id: number
          is_active: boolean | null
          name: string
          total_credits: number
          total_semesters: number
          university_id: number
          updated_at: string | null
          year: number
        }
        Insert: {
          code: string
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          name: string
          total_credits: number
          total_semesters: number
          university_id: number
          updated_at?: string | null
          year: number
        }
        Update: {
          code?: string
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          name?: string
          total_credits?: number
          total_semesters?: number
          university_id?: number
          updated_at?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "curricula_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      curriculum_courses: {
        Row: {
          course_name: string
          created_at: string | null
          credits: number
          curriculum_id: number
          elective_group: string | null
          id: number
          is_active: boolean | null
          is_elective: boolean | null
          linked_course_id: number | null
          semester: number
          updated_at: string | null
        }
        Insert: {
          course_name: string
          created_at?: string | null
          credits?: number
          curriculum_id: number
          elective_group?: string | null
          id?: number
          is_active?: boolean | null
          is_elective?: boolean | null
          linked_course_id?: number | null
          semester: number
          updated_at?: string | null
        }
        Update: {
          course_name?: string
          created_at?: string | null
          credits?: number
          curriculum_id?: number
          elective_group?: string | null
          id?: number
          is_active?: boolean | null
          is_elective?: boolean | null
          linked_course_id?: number | null
          semester?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "curriculum_courses_curriculum_id_fkey"
            columns: ["curriculum_id"]
            isOneToOne: false
            referencedRelation: "curricula"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curriculum_courses_linked_course_id_fkey"
            columns: ["linked_course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      curriculum_prerequisites: {
        Row: {
          created_at: string | null
          curriculum_course_id: number
          id: number
          is_active: boolean | null
          prerequisite_course_id: number | null
          prerequisite_type: string
          required_credits: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          curriculum_course_id: number
          id?: number
          is_active?: boolean | null
          prerequisite_course_id?: number | null
          prerequisite_type?: string
          required_credits?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          curriculum_course_id?: number
          id?: number
          is_active?: boolean | null
          prerequisite_course_id?: number | null
          prerequisite_type?: string
          required_credits?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "curriculum_prerequisites_curriculum_course_id_fkey"
            columns: ["curriculum_course_id"]
            isOneToOne: false
            referencedRelation: "curriculum_courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curriculum_prerequisites_prerequisite_course_id_fkey"
            columns: ["prerequisite_course_id"]
            isOneToOne: false
            referencedRelation: "curriculum_courses"
            referencedColumns: ["id"]
          },
        ]
      }
      friend_requests: {
        Row: {
          created_at: string | null
          id: number
          message: string | null
          receiver_id: string | null
          responded_at: string | null
          sender_id: string | null
          status: string
        }
        Insert: {
          created_at?: string | null
          id?: number
          message?: string | null
          receiver_id?: string | null
          responded_at?: string | null
          sender_id?: string | null
          status?: string
        }
        Update: {
          created_at?: string | null
          id?: number
          message?: string | null
          receiver_id?: string | null
          responded_at?: string | null
          sender_id?: string | null
          status?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string | null
          curriculum_id: number | null
          description: string | null
          first_name: string | null
          id: string
          last_name: string | null
          nickname: string | null
          profile_photo: string | null
          role: string
          student_id: string | null
          university_id: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          curriculum_id?: number | null
          description?: string | null
          first_name?: string | null
          id: string
          last_name?: string | null
          nickname?: string | null
          profile_photo?: string | null
          role?: string
          student_id?: string | null
          university_id?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          curriculum_id?: number | null
          description?: string | null
          first_name?: string | null
          id?: string
          last_name?: string | null
          nickname?: string | null
          profile_photo?: string | null
          role?: string
          student_id?: string | null
          university_id?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_curriculum_id_fkey"
            columns: ["curriculum_id"]
            isOneToOne: false
            referencedRelation: "curricula"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      schedules: {
        Row: {
          combination_data: Json
          created_at: string | null
          id: string
          is_favorite: boolean
          is_public: boolean
          name: string | null
          share_token: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          combination_data: Json
          created_at?: string | null
          id?: string
          is_favorite?: boolean
          is_public?: boolean
          name?: string | null
          share_token?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          combination_data?: Json
          created_at?: string | null
          id?: string
          is_favorite?: boolean
          is_public?: boolean
          name?: string | null
          share_token?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      sections: {
        Row: {
          capacity: number | null
          course_id: number
          created_at: string | null
          enrolled: number | null
          id: number
          is_active: boolean | null
          professor: string | null
          professor_email: string | null
          section_number: string
          updated_at: string | null
          waitlisted: number | null
        }
        Insert: {
          capacity?: number | null
          course_id: number
          created_at?: string | null
          enrolled?: number | null
          id?: number
          is_active?: boolean | null
          professor?: string | null
          professor_email?: string | null
          section_number: string
          updated_at?: string | null
          waitlisted?: number | null
        }
        Update: {
          capacity?: number | null
          course_id?: number
          created_at?: string | null
          enrolled?: number | null
          id?: number
          is_active?: boolean | null
          professor?: string | null
          professor_email?: string | null
          section_number?: string
          updated_at?: string | null
          waitlisted?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "sections_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          building: string | null
          created_at: string | null
          day: string
          end_time: string
          frequency: string | null
          id: number
          is_active: boolean | null
          location: string | null
          modality: string | null
          room: string | null
          section_id: number
          session_type: string
          start_time: string
          updated_at: string | null
        }
        Insert: {
          building?: string | null
          created_at?: string | null
          day: string
          end_time: string
          frequency?: string | null
          id?: number
          is_active?: boolean | null
          location?: string | null
          modality?: string | null
          room?: string | null
          section_id: number
          session_type: string
          start_time: string
          updated_at?: string | null
        }
        Update: {
          building?: string | null
          created_at?: string | null
          day?: string
          end_time?: string
          frequency?: string | null
          id?: number
          is_active?: boolean | null
          location?: string | null
          modality?: string | null
          room?: string | null
          section_id?: number
          session_type?: string
          start_time?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sessions_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "sections"
            referencedColumns: ["id"]
          },
        ]
      }
      universities: {
        Row: {
          created_at: string | null
          id: number
          is_active: boolean | null
          name: string
          parsing_config: string | null
          semester_info: string | null
          short_name: string
          time_format: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          name: string
          parsing_config?: string | null
          semester_info?: string | null
          short_name: string
          time_format?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: number
          is_active?: boolean | null
          name?: string
          parsing_config?: string | null
          semester_info?: string | null
          short_name?: string
          time_format?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      user_curriculum_progress: {
        Row: {
          completed_at: string | null
          created_at: string | null
          curriculum_course_id: number
          curriculum_id: number
          grade: string | null
          id: number
          is_active: boolean | null
          linked_course_override: number | null
          planned_period: string | null
          status: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string | null
          curriculum_course_id: number
          curriculum_id: number
          grade?: string | null
          id?: number
          is_active?: boolean | null
          linked_course_override?: number | null
          planned_period?: string | null
          status?: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string | null
          curriculum_course_id?: number
          curriculum_id?: number
          grade?: string | null
          id?: number
          is_active?: boolean | null
          linked_course_override?: number | null
          planned_period?: string | null
          status?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_curriculum_progress_curriculum_course_id_fkey"
            columns: ["curriculum_course_id"]
            isOneToOne: false
            referencedRelation: "curriculum_courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_curriculum_progress_curriculum_id_fkey"
            columns: ["curriculum_id"]
            isOneToOne: false
            referencedRelation: "curricula"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_curriculum_progress_linked_course_override_fkey"
            columns: ["linked_course_override"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
