"""Add combination_data column to schedules

Revision ID: 64bd12fc7867
Revises: 8c1f2d4a9b6e
Create Date: 2026-03-11 00:28:46.218071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bd12fc7867'
down_revision: Union[str, Sequence[str], None] = '8c1f2d4a9b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('combination_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'combination_data')
    # ### end Alembic commands ###
