"""add_curriculum_tables

Revision ID: cd011304f3ab
Revises: 64bd12fc7867
Create Date: 2026-03-11 11:57:44.959355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd011304f3ab'
down_revision: Union[str, Sequence[str], None] = '64bd12fc7867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curricula',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('total_semesters', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_curricula_id'), 'curricula', ['id'], unique=False)
    op.create_table('curriculum_courses',
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('elective_group', sa.String(length=50), nullable=True),
    sa.Column('linked_course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_curriculum_courses_id'), 'curriculum_courses', ['id'], unique=False)
    op.create_table('curriculum_prerequisites',
    sa.Column('curriculum_course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_type', sa.String(length=20), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['curriculum_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_curriculum_prerequisites_id'), 'curriculum_prerequisites', ['id'], unique=False)
    op.create_table('user_curriculum_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'curriculum_course_id', name='uq_user_curriculum_course'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_curriculum_progress_id'), 'user_curriculum_progress', ['id'], unique=False)
    op.add_column('users', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'curricula', ['curriculum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'curriculum_id')
    op.drop_index(op.f('ix_user_curriculum_progress_id'), table_name='user_curriculum_progress')
    op.drop_table('user_curriculum_progress')
    op.drop_index(op.f('ix_curriculum_prerequisites_id'), table_name='curriculum_prerequisites')
    op.drop_table('curriculum_prerequisites')
    op.drop_index(op.f('ix_curriculum_courses_id'), table_name='curriculum_courses')
    op.drop_table('curriculum_courses')
    op.drop_index(op.f('ix_curricula_id'), table_name='curricula')
    op.drop_table('curricula')
    # ### end Alembic commands ###
