-- ============================================================================
-- schedule-maker-2 :: initial Supabase schema
-- Migrates the app off the FastAPI/SQLAlchemy + Railway Postgres backend.
--
-- Design notes:
--   * Catalog tables (universities, courses, sections, sessions, curricula,
--     curriculum_courses, curriculum_prerequisites) mirror backend/app/models/*.py
--     column-for-column so `pg_dump --data-only --column-inserts` from the old
--     Railway Postgres can be replayed directly against these tables.
--   * `users` (old FastAPI table) is replaced by Supabase `auth.users` +
--     `public.profiles`. Anything that referenced users.id (int) now
--     references auth.users(id) (uuid). Old integer user data cannot be
--     restored as-is into these uuid columns -- it must be remapped during
--     migration (out of scope for this file).
--   * `schedule_sessions` join table is intentionally dropped -- schedules now
--     store their session combination directly in `combination_data` jsonb.
--   * `friendships` table is intentionally dropped -- "are we friends" is
--     derived from an accepted row in `friend_requests` (either direction),
--     per the RLS policies below. There is no separate friendships table.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. Extensions
-- ----------------------------------------------------------------------------
create extension if not exists pgcrypto; -- gen_random_uuid()

-- ----------------------------------------------------------------------------
-- 1. Shared trigger function: keep updated_at current
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================================
-- 2. Catalog tables (dependency order)
-- ============================================================================

-- 2.1 universities ------------------------------------------------------------
create table if not exists public.universities (
  id             integer generated by default as identity primary key,
  name           varchar(255) not null unique,
  short_name     varchar(50)  not null unique,
  time_format    varchar(20) default 'hours',
  semester_info  text,
  parsing_config text,
  is_active      boolean default true,
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

create trigger set_updated_at
  before update on public.universities
  for each row execute function public.set_updated_at();

-- 2.2 courses ------------------------------------------------------------------
create table if not exists public.courses (
  id            integer generated by default as identity primary key,
  university_id integer not null references public.universities(id),
  code          varchar(20)  not null,
  name          varchar(255) not null,
  description   text,
  department    varchar(100), -- career codes like 'CS', 'DS', 'BIO'
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

create trigger set_updated_at
  before update on public.courses
  for each row execute function public.set_updated_at();

-- 2.3 sections -------------------------------------------------------------
create table if not exists public.sections (
  id               integer generated by default as identity primary key,
  course_id        integer not null references public.courses(id) on delete cascade,
  section_number   varchar(10) not null,
  capacity         integer default 30,
  enrolled         integer default 0,
  waitlisted       integer default 0,
  professor        varchar(255),
  professor_email  varchar(255),
  is_active        boolean default true,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

create trigger set_updated_at
  before update on public.sections
  for each row execute function public.set_updated_at();

-- 2.4 sessions -------------------------------------------------------------
-- (public.sessions -- no clash with auth.sessions, different schema)
create table if not exists public.sessions (
  id           integer generated by default as identity primary key,
  section_id   integer not null references public.sections(id) on delete cascade,
  session_type varchar(50) not null,
  day          varchar(10) not null,
  start_time   time not null,
  end_time     time not null,
  location     varchar(255),
  building     varchar(100),
  room         varchar(50),
  modality     varchar(50) default 'Presencial',
  frequency    varchar(50) default 'Semanal',
  is_active    boolean default true,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create trigger set_updated_at
  before update on public.sessions
  for each row execute function public.set_updated_at();

-- 2.5 curricula --------------------------------------------------------------
create table if not exists public.curricula (
  id              integer generated by default as identity primary key,
  university_id   integer not null references public.universities(id),
  name            varchar(255) not null,
  code            varchar(50)  not null unique,
  year            integer not null,
  total_credits   integer not null,
  total_semesters integer not null,
  is_active       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create trigger set_updated_at
  before update on public.curricula
  for each row execute function public.set_updated_at();

-- 2.6 curriculum_courses -----------------------------------------------------
create table if not exists public.curriculum_courses (
  id               integer generated by default as identity primary key,
  curriculum_id    integer not null references public.curricula(id) on delete cascade,
  course_name      varchar(255) not null,
  semester         integer not null,
  credits          integer not null default 0,
  is_elective      boolean default false,
  elective_group   varchar(50),
  linked_course_id integer references public.courses(id) on delete set null,
  is_active        boolean default true,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

create trigger set_updated_at
  before update on public.curriculum_courses
  for each row execute function public.set_updated_at();

-- 2.7 curriculum_prerequisites ------------------------------------------------
create table if not exists public.curriculum_prerequisites (
  id                     integer generated by default as identity primary key,
  curriculum_course_id   integer not null references public.curriculum_courses(id) on delete cascade,
  prerequisite_course_id integer references public.curriculum_courses(id) on delete cascade,
  prerequisite_type      varchar(20) not null default 'course', -- 'course' or 'credits'
  required_credits       integer,
  is_active              boolean default true,
  created_at             timestamptz default now(),
  updated_at             timestamptz default now()
);

create trigger set_updated_at
  before update on public.curriculum_prerequisites
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 3. profiles (replaces old `users` table; identity now lives in auth.users)
-- ============================================================================
create table if not exists public.profiles (
  id             uuid primary key references auth.users(id) on delete cascade,
  first_name     text,
  last_name      text,
  nickname       text,
  profile_photo  text,
  description    text,
  student_id     text,
  university_id  integer references public.universities(id),
  curriculum_id  integer references public.curricula(id),
  role           text not null default 'student',
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

create trigger set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create a profile row for every new auth.users row, including
-- anonymous sign-ins -- every profile column besides id/role is nullable.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'student');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- 4. schedules (replaces schedules + schedule_sessions)
-- ============================================================================
create table if not exists public.schedules (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  name              text,
  combination_data  jsonb not null,
  share_token       uuid unique default gen_random_uuid(),
  is_public         boolean not null default false,
  is_favorite       boolean not null default false,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create trigger set_updated_at
  before update on public.schedules
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 5. friend_requests (replaces friend_requests + friendships)
-- ============================================================================
create table if not exists public.friend_requests (
  id            bigint generated by default as identity primary key,
  sender_id     uuid references auth.users(id) on delete cascade,
  receiver_id   uuid references auth.users(id) on delete cascade,
  status        text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  message       text,
  responded_at  timestamptz,
  created_at    timestamptz default now(),
  unique (sender_id, receiver_id),
  check (sender_id <> receiver_id)
);

-- ============================================================================
-- 6. user_curriculum_progress
-- ============================================================================
create table if not exists public.user_curriculum_progress (
  id                        integer generated by default as identity primary key,
  user_id                   uuid not null references auth.users(id) on delete cascade,
  curriculum_id             integer not null references public.curricula(id) on delete cascade,
  curriculum_course_id      integer not null references public.curriculum_courses(id) on delete cascade,
  status                    text not null default 'pending', -- 'completed', 'in_progress', 'pending'
  completed_at              timestamptz,
  grade                     text,
  planned_period            text, -- e.g. '2026-2'
  linked_course_override    integer references public.courses(id) on delete set null,
  is_active                 boolean default true,
  created_at                timestamptz default now(),
  updated_at                timestamptz default now(),
  unique (user_id, curriculum_course_id)
);

create trigger set_updated_at
  before update on public.user_curriculum_progress
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 7. Indexes
-- ============================================================================
create index if not exists idx_sections_course_id on public.sections(course_id);
create index if not exists idx_sessions_section_id on public.sessions(section_id);
create index if not exists idx_curriculum_courses_curriculum_id on public.curriculum_courses(curriculum_id);
create index if not exists idx_curriculum_prereq_curriculum_course_id on public.curriculum_prerequisites(curriculum_course_id);
create index if not exists idx_curriculum_prereq_prerequisite_course_id on public.curriculum_prerequisites(prerequisite_course_id);
create index if not exists idx_schedules_user_id on public.schedules(user_id);
create index if not exists idx_schedules_share_token on public.schedules(share_token);
create index if not exists idx_friend_requests_receiver_status on public.friend_requests(receiver_id, status);
create index if not exists idx_user_curriculum_progress_user_id on public.user_curriculum_progress(user_id);

-- ============================================================================
-- 8. Row Level Security
-- ============================================================================

-- 8.1 Catalog tables: public read-only. Writes happen via service role
--     (migration scripts, admin tooling), which bypasses RLS entirely --
--     no insert/update/delete policies are defined here on purpose.
alter table public.universities             enable row level security;
alter table public.courses                  enable row level security;
alter table public.sections                 enable row level security;
alter table public.sessions                 enable row level security;
alter table public.curricula                enable row level security;
alter table public.curriculum_courses       enable row level security;
alter table public.curriculum_prerequisites enable row level security;

create policy "catalog read: universities" on public.universities
  for select to anon, authenticated using (true);
create policy "catalog read: courses" on public.courses
  for select to anon, authenticated using (true);
create policy "catalog read: sections" on public.sections
  for select to anon, authenticated using (true);
create policy "catalog read: sessions" on public.sessions
  for select to anon, authenticated using (true);
create policy "catalog read: curricula" on public.curricula
  for select to anon, authenticated using (true);
create policy "catalog read: curriculum_courses" on public.curriculum_courses
  for select to anon, authenticated using (true);
create policy "catalog read: curriculum_prerequisites" on public.curriculum_prerequisites
  for select to anon, authenticated using (true);

-- 8.2 profiles
alter table public.profiles enable row level security;

create policy "profiles: select for authenticated" on public.profiles
  for select to authenticated using (true);

create policy "profiles: update own row" on public.profiles
  for update to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- 8.3 schedules
alter table public.schedules enable row level security;

create policy "schedules: owner full access" on public.schedules
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "schedules: public read" on public.schedules
  for select to anon, authenticated
  using (is_public = true);

create policy "schedules: friends read" on public.schedules
  for select to authenticated
  using (
    exists (
      select 1 from public.friend_requests fr
      where fr.status = 'accepted'
        and (
          (fr.sender_id = auth.uid() and fr.receiver_id = schedules.user_id)
          or
          (fr.receiver_id = auth.uid() and fr.sender_id = schedules.user_id)
        )
    )
  );

-- 8.4 friend_requests
alter table public.friend_requests enable row level security;

create policy "friend_requests: select participants" on public.friend_requests
  for select to authenticated
  using (auth.uid() in (sender_id, receiver_id));

create policy "friend_requests: insert as sender, not anonymous" on public.friend_requests
  for insert to authenticated
  with check (
    auth.uid() = sender_id
    and coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false
  );

create policy "friend_requests: update by receiver" on public.friend_requests
  for update to authenticated
  using (auth.uid() = receiver_id)
  with check (auth.uid() = receiver_id);

create policy "friend_requests: delete by participants" on public.friend_requests
  for delete to authenticated
  using (auth.uid() in (sender_id, receiver_id));

-- 8.5 user_curriculum_progress
alter table public.user_curriculum_progress enable row level security;

create policy "user_curriculum_progress: owner full access" on public.user_curriculum_progress
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ============================================================================
-- 9. Storage: avatars bucket
-- ============================================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

create policy "avatars: public read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'avatars');

create policy "avatars: owner insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatars: owner update" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatars: owner delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
